---
User: 
  - id:                        1
    login:                     quentin
    email:                     quentin@example.com
    salt:                      356a192b7913b04c54574d18c28d46e6395428ab # SHA1('0')
    password:                  monkey
    created_at:                <%= 5.days.ago.to_s :db  %>
    remember_token_expires_at: <%= 1.days.from_now.to_s %>
    remember_token:            77de68daecd823babbb58edb1c8e14d7106e83bb
  - id:                        2
    login:                     aaron
    email:                     aaron@example.com
    salt:                      da4b9237bacccdf19c0760cab7aec4a8359010b0 # SHA1('1')
    password:                  monkey
    created_at:                <%= 1.days.ago.to_s :db %>
    remember_token_expires_at: 
    remember_token:            
  - id:                        3
    login:                     old_password_holder
    email:                     salty_dog@example.com
    salt:                      356a192b7913b04c54574d18c28d46e6395428ab # SHA1('0')
    password:                  monkey
    created_at:                <%= 1.days.ago.to_s :db %>

CanonicalForm:
  - id: 1
    name: "Adnaria frondosa"
  - id: 2
    name: "Adnatosphaeridium tutulosum"
  - id: 3
    name: "Adnatosphaeridium"
  - id: 4
    name: "Dadoychus flavocinctus"
  - id: 5
    name: "Dadoychus mucuim"
  - id: 6
    name: "Higehananomia"
  - id: 7
    name: "Higehananomia palpalis"
  - id: 8
    name: "Higena"
  - id: 9
    name: "Higena distincta"
  - id: 10
    name: "Higena plumigera"
  - id: 11
    name: "Hegena"

NameString:
  - id: 1
    name: "Adnaria frondosa (L.) Kuntze"
    canonical_form_id: 1
  - id: 2
    name: "Adnatosphaeridium tutulosum (Cookson & Eisenack 1960)"
    canonical_form_id: 2
  - id: 3
    name: "Adnatosphaeridium G. Williams et Downie, 1966"
    canonical_form_id: 3
  - id: 4
    name: "Dadoychus flavocinctus Monné & Giesbert, 1994"
    canonical_form_id: 4
  - id: 5
    name: "Dadoychus mucuim Júlio, Giorgi & Monné, 2000"
    canonical_form_id: 5
  - id: 6
    name: "Higehananomia Kôno 1935"
    canonical_form_id: 6
  - id: 7
    name: "Higehananomia palpalis"
    canonical_form_id: 7
  - id: 8
    name: "Higehananomia palpalis Kono 1935"
    canonical_form_id: 7
  - id: 9
    name: "Higena"
    canonical_form_id: 8
  - id: 10
    name: "Higena distincta"
    canonical_form_id: 9
  - id: 11
    name: "Higena Matsumura 1925"
    canonical_form_id: 8
  - id: 12
    name: "Higena plumigera"
    canonical_form_id: 10
  - id: 13
    name: "Higena plumigera Matsumura 1925"
    canonical_form_id: 10
  - id: 14
    name: "Higena plumigera Linneaus 1787"
    canonical_form_id: 10
  - id: 15
    name: "Higena plumigera L. 1787"
    canonical_form_id: 10
  - id: 16
    name: "Higena plumigera Linn."
    canonical_form_id: 10
  - id: 17
    name: "Hegena Matsumura 1925"
    canonical_form_id: 11

LexicalGroup:
  - id: 1
    supercedure_id:
  - id: 2
    supercedure_id:
  - id: 3
    supercedure_id:
  - id: 4
    supercedure_id:

LexicalGroupNameString:
  - id: 1
    lexical_group_id: 1
    name_string_id: 7
  - id: 2
    lexical_group_id: 1
    name_string_id: 8
  - id: 3 
    lexical_group_id: 2
    name_string_id: 9
  - id: 4 
    lexical_group_id: 2
    name_string_id: 11
  - id: 5
    lexical_group_id: 3
    name_string_id: 12
  - id: 6 
    lexical_group_id: 4
    name_string_id: 12
  - id: 7 
    lexical_group_id: 3
    name_string_id: 13
  - id: 8 
    lexical_group_id: 4
    name_string_id: 14
  - id: 9
    lexical_group_id: 4
    name_string_id: 15
  - id: 10
    lexical_group_id: 4
    name_string_id: 16
  - id: 11
    lexical_group_id: 2
    name_string_id: 17

Kingdom:
  - id: 1
    name: Animalia
  - id: 2
    name: Plantae
  - id: 3
    name: Fungi

NameRank:
  - id: 1
    name: Genus
  - id: 2
    name: Species

DataSource: 
  - id: 1
    title: "ITIS"
    logo_url: "http://www.google.com/intl/en_ALL/images/logo.gif"
    refresh_period_days: 14
  - id: 2
    title: "IPNI"
    refresh_period_days: 14
  - id: 3
    title: "Index Fungorum"
    refresh_period_days: 14
  - id: 4
    title: "Name Bank"
    refresh_period_days: 14
  - id: 5
    title: "Encyclopedia of Life"
    refresh_period_days: 14
  - id: 6
    title: "FishBase"
    refresh_period_days: 0
  - id: 7
    title: "Tropicos"
    refresh_period_days: 14
  

DataSourceContributor:
  - user_id: 2 #aaron
    data_source_id: 1 #ITIS
    data_source_admin: 1
  - user_id: 1 #quentin 
    data_source_id: 1 #ITIS
  - user_id: 1 #quentin 
    data_source_id: 2 #IPNI
  - user_id: 2 #aaron
    data_source_id: 3 #Index Fungorum
  - user_id: 2 #aaron
    data_source_id: 4 #Name Bank
  - user_id: 2 #aaron
    data_source_id: 5 #Encyclopedia of Life
  - user_id: 2 #aaron
    data_source_id: 7 #Tropicos
    
ImportScheduler:
  - data_source_id: 1
    status: 4
    message: 'Updated'
  - data_source_id: 2
    status: 4
    message: 'Updated'
  - data_source_id: 3
    status: 4
    message: 'Updated'
  - data_source_id: 4
    status: 4
    message: 'Updated'    
  - data_source_id: 5
    status: 4
    message: 'Updated'    

NameIndex:
  - id: 1
    name_string_id: 1
    data_source_id: 1
  - id: 2
    name_string_id: 1
    data_source_id: 2
  - id: 3
    name_string_id: 1
    data_source_id: 3
  - id: 4
    name_string_id: 2
    data_source_id: 1
  - id: 5
    name_string_id: 2
    data_source_id: 3
  - id: 6
    name_string_id: 3
    data_source_id: 5
  - id: 7
    name_string_id: 3
    data_source_id: 4
  - id: 8
    name_string_id: 7
    data_source_id: 2
  - id: 9
    name_string_id: 9
    data_source_id: 2
  - id: 10
    name_string_id: 10
    data_source_id: 2
  - id: 11
    name_string_id: 11
    data_source_id: 2
  - id: 12
    name_string_id: 12
    data_source_id: 2
  - id: 13
    name_string_id: 13
    data_source_id: 2
  - id: 14
    name_string_id: 14
    data_source_id: 2
  - id: 15
    name_string_id: 15 #lexical group match, not strict match
    data_source_id: 4
  - id: 16
    name_string_id: 16 #lexical group match, not strict match
    data_source_id: 4
  - id: 17
    name_string_id: 4
    data_source_id: 4
  - id: 18
    name_string_id: 17 #lexical group match, not strict match
    data_source_id: 4 
  - id: 19
    name_string_id: 7 #strict match
    data_source_id: 4    

NameIndexRecord:
  - name_index_id: 1
  - name_index_id: 1
  - name_index_id: 2
  - name_index_id: 3
  - name_index_id: 4
  - name_index_id: 4
  - name_index_id: 4
  - name_index_id: 5
  - name_index_id: 6
  - name_index_id: 7
  - name_index_id: 7
  - name_index_id: 7
  - name_index_id: 7
  - name_index_id: 7
  - name_index_id: 7
  - name_index_id: 8
  - name_index_id: 9
  - name_index_id: 10
  - name_index_id: 11
  - name_index_id: 12
  - name_index_id: 13
  - name_index_id: 14
  - name_index_id: 15
  - name_index_id: 16
  
NameWord:
  - id: 1
    word: Adnaria
  - id: 2
    word: frondosa
  - id: 3
    word: L
  - id: 4
    word: Kuntze
  - id: 5
    word: Adnatosphaeridium
  - id: 6
    word: tutulosum
  - id: 7
    word: Cookson
  - id: 8
    word: Eisenack
  - id: 9
    word: 1960
  - id: 10
    word: G
  - id: 11
    word: Williams
  - id: 12
    word: Downie
  - id: 13
    word: 1966
  - id: 14
    word: Dadoychus
  - id: 15
    word: flavocinctus
  - id: 16
    word: Monné
  - id: 17
    word: Giesbert
  - id: 18
    word: 1994
  - id: 19
    word: mucuim
  - id: 20
    word: Júlio
  - id: 21
    word: Giorgi
  - id: 22
    word: 2000
  - id: 23
    word: Higehananomia
  - id: 24
    word: Kôno
  - id: 25
    word: 1935
  - id: 26
    word: palpalis
  - id: 27
    word: Kono
  - id: 28
    word: Higena
  - id: 29
    word: distincta
  - id: 30
    word: Matsumura
  - id: 31
    word: 1925
  - id: 32
    word: plumigera
  - id: 33
    word: Linneaus
  - id: 34
    word: 1787
  - id: 35
    word: Linn
  - id: 36
    word: Hegena
  
SemanticMeaning:
  - id: 1
    name: uninomial
  - id: 2
    name: genus
  - id: 3
    name: species
  - id: 4
    name: infraspecies
  - id: 5
    name: author_word
  - id: 6
    name: year
  
